language: node_js
node_js: 8.9.3

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

after_script:
  - cd dist
  - git init
  - git config user.name "weineel"
  - git config user.email "LiJF_wn@163.com"
  - git add .
  - git commit -m "Update resume"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/weineel/resume.git
   # 设置一个加密的环境变量，GH_TOKEN环境变量的值
   - secure: "bkha8ZAutOOW0FsWrpxELZ5G2/yjaQFM2AjmdHSxrjmKCiOt9GlxXRjTW7krdejAhmUjXF85uygpcl0d15AFqAjDwiyYXKEYHFA9U8kCxq3PwiAvB8eJ1iU5SIga53R82idl4erC2MEz6g3PzwvwFcm8ka9PpqlwuDqnRL6PRvHhrUdLaTJt8M56no6YoT1SYPUfN7t3DqXRl4WZ4PmA6INVmBBm/DEHgD9Ituhb/o3cdO9kT2RMuo65Z+4oj2G08/W2QJ8Ul4CzigtAB1nnnz/g/3ufWsNr7QdprLowzmYyuUxIvffB1G3GKHDD27AUaocBgOGaRyvAaZqjbfw8Wd/y/ZkznaQmr2/GAaD25Mpi3ckZNOJtzhOYUL9Vf/iHKUAtecGumWpQQN0FCYwjMQ8TrVjQWez/kg8bAd5gm6zxThfmoAr5h6JjuI6VKAq3a6Ko9LYDX25PNTJXRBtLe4fuTCJ6bjoD9Oi/MgsdlYeEIsTG2VJB/Yev6upiXifAKHwe97okh69oopkC4f9QksU++0uyJj9BwyHRqS+A8TecOhVultaVHkdoho11oDrMX+0P5fSDP4jrzLPiSCzdj8wxvL1nt9W6/KJXBVz2u1rucgJtWS/7Hj1m0YxtgCuiYlvlqEcFJtzRKt6Z7aw6/qgqzKHaBfkcA4bhKsUEcbc="